NIFTY_50 = [
    "RELIANCE.NS",
    "TCS.NS",
    "HDFCBANK.NS",
    "INFY.NS",
    "ICICIBANK.NS",
    "HINDUNILVR.NS",
    "ITC.NS",
    "SBIN.NS",
    "BHARTIARTL.NS",
    "KOTAKBANK.NS",
    "LT.NS",
    "AXISBANK.NS",
    "MARUTI.NS",
    "TITAN.NS",
    "SUNPHARMA.NS",
    "WIPRO.NS",
    "BAJFINANCE.NS",
    "NTPC.NS",
    "ONGC.NS",
    "HCLTECH.NS",
    "TMPV.NS",
    "TATASTEEL.NS",
    "JSWSTEEL.NS",
    "HINDALCO.NS",
    "COALINDIA.NS",
    "ADANIPORTS.NS",
    "BAJAJFINSV.NS",
    "BPCL.NS",
    "BRITANNIA.NS",
    "CIPLA.NS",
    "DRREDDY.NS",
    "EICHERMOT.NS",
    "GRASIM.NS",
    "HEROMOTOCO.NS",
    "INDUSINDBK.NS",
    "TECHM.NS",
    "ASIANPAINT.NS",
    "DIVISLAB.NS",
    "NESTLEIND.NS",
    "POWERGRID.NS",
    "ULTRACEMCO.NS",
    "TATACONSUM.NS",
    "APOLLOHOSP.NS",
    "HDFCLIFE.NS",
    "SBILIFE.NS",
    "ADANIENT.NS",
    "BAJAJ-AUTO.NS",
    "M&M.NS",
    "SHRIRAMFIN.NS",
    "TRENT.NS",
]

SECTOR_MAP = {
    "RELIANCE.NS": "Energy",
    "ONGC.NS": "Energy",
    "BPCL.NS": "Energy",
    "TCS.NS": "IT",
    "INFY.NS": "IT",
    "WIPRO.NS": "IT",
    "HCLTECH.NS": "IT",
    "TECHM.NS": "IT",
    "HDFCBANK.NS": "Banking",
    "ICICIBANK.NS": "Banking",
    "SBIN.NS": "Banking",
    "KOTAKBANK.NS": "Banking",
    "AXISBANK.NS": "Banking",
    "INDUSINDBK.NS": "Banking",
    "BAJFINANCE.NS": "NBFC",
    "BAJAJFINSV.NS": "NBFC",
    "HDFCLIFE.NS": "Insurance",
    "SBILIFE.NS": "Insurance",
    "LT.NS": "Infra",
    "ADANIPORTS.NS": "Infra",
    "POWERGRID.NS": "Power",
    "NTPC.NS": "Power",
    "TATASTEEL.NS": "Metals",
    "JSWSTEEL.NS": "Metals",
    "HINDALCO.NS": "Metals",
    "COALINDIA.NS": "Metals",
    "SUNPHARMA.NS": "Pharma",
    "DRREDDY.NS": "Pharma",
    "CIPLA.NS": "Pharma",
    "DIVISLAB.NS": "Pharma",
    "APOLLOHOSP.NS": "Pharma",
    "MARUTI.NS": "Auto",
    "TMPV.NS": "Auto",
    "EICHERMOT.NS": "Auto",
    "HEROMOTOCO.NS": "Auto",
    "HINDUNILVR.NS": "FMCG",
    "ITC.NS": "FMCG",
    "NESTLEIND.NS": "FMCG",
    "BRITANNIA.NS": "FMCG",
    "TATACONSUM.NS": "FMCG",
    "ASIANPAINT.NS": "Paints",
    "TITAN.NS": "Consumer",
    "GRASIM.NS": "Cement",
    "ULTRACEMCO.NS": "Cement",
    "BHARTIARTL.NS": "Telecom",
}

SYM_MAP = {
    "NIFTY": "^NSEI",
    "BANKNIFTY": "^NSEBANK",
    "FINNIFTY": "^CNXFIN",
    "MIDCPNIFTY": "^NSEMDCP50",
    "SENSEX": "^BSESN",
}
